
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqrmgarnvjtltfpboixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxcm1nYXJudmp0bHRmcGJvaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI1MTEsImV4cCI6MjA1ODY4ODUxMX0.Es8PhuCeLKUQYSvENkvtvTSOTX31dDZ-Czf2-rS2964";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom type declarations for our expenses tables since they may not be in the generated types yet
declare module '@supabase/supabase-js' {
  interface Database {
    public: {
      Tables: {
        // Include existing tables
        calendar_events: any;
        note_categories: any;
        notes: any;
        reading_references: any;
        todos: any;
        // Add our new tables
        expenses: {
          Row: {
            id: string;
            user_id: string;
            amount: number;
            category: string;
            description: string | null;
            date: string;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            amount: number;
            category: string;
            description?: string | null;
            date?: string;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            amount?: number;
            category?: string;
            description?: string | null;
            date?: string;
            created_at?: string;
          };
        };
        expense_categories: {
          Row: {
            id: string;
            user_id: string;
            name: string;
            color: string;
            icon: string | null;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            name: string;
            color: string;
            icon?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            name?: string;
            color?: string;
            icon?: string | null;
            created_at?: string;
          };
        };
        // Add investments tables
        investments: {
          Row: {
            id: string;
            user_id: string;
            symbol: string;
            shares: number;
            purchase_price: number;
            purchase_date: string;
            notes: string | null;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            symbol: string;
            shares: number;
            purchase_price: number;
            purchase_date: string;
            notes?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            symbol?: string;
            shares?: number;
            purchase_price?: number;
            purchase_date?: string;
            notes?: string | null;
            created_at?: string;
          };
        };
      };
    };
  }
}
