// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqrmgarnvjtltfpboixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxcm1nYXJudmp0bHRmcGJvaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI1MTEsImV4cCI6MjA1ODY4ODUxMX0.Es8PhuCeLKUQYSvENkvtvTSOTX31dDZ-Czf2-rS2964";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);